/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedGeradorRouteImport } from './routes/_authenticated/gerador'
import { Route as AuthenticatedMissoesRouteImport } from './routes/_authenticated/missoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGeradorRoute = AuthenticatedGeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissoesRoute = AuthenticatedMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gerador': typeof AuthenticatedGeradorRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/radar': typeof AuthenticatedRadarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gerador': typeof AuthenticatedGeradorRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/radar': typeof AuthenticatedRadarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/gerador': typeof AuthenticatedGeradorRoute
  '/_authenticated/missoes': typeof AuthenticatedMissoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/gerador' | '/missoes' | '/painel' | '/projetos' | '/radar'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/gerador' | '/missoes' | '/painel' | '/projetos' | '/radar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/gerador'
    | '/_authenticated/missoes'
    | '/_authenticated/painel'
    | '/_authenticated/projetos'
    | '/_authenticated/radar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gerador': {
      id: '/_authenticated/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof AuthenticatedGeradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes': {
      id: '/_authenticated/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof AuthenticatedMissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGeradorRoute: typeof AuthenticatedGeradorRoute
  AuthenticatedMissoesRoute: typeof AuthenticatedMissoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGeradorRoute: AuthenticatedGeradorRoute,
  AuthenticatedMissoesRoute: AuthenticatedMissoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
